---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../packagesfiles

- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages|default([]) }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Ensure required packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages|default([]) }}"
  when: ansible_os_family == "Debian"
  become: true
# - name: Upgrade all packages (yum)
#   yum: name=* state=latest
#   when: ansible_os_family == "RedHat"

# - name: Upgrade all packages (apt)
#   apt: upgrade=dist
#   when: ansible_os_family == "Debian"

