---
# Common Tasks

- name: Ensure zookeeper host exists
  fail: msg="One, or no zookeeper host may be specified."
  when: "groups.get('zookeeper_servers', [])|length < 1"

- name: Ensure kafka host exists
  fail: msg="One, or no kafka host may be specified."
  when: "groups.get('kafka_servers', [])|length < 1"

- name: Close old control master
  raw: ps aux | grep ansible-ssh | grep -v grep | awk '{print $2}' | xargs kill -9 ; true
  ignore_errors: true
  changed_when: false
  vars:
    ansible_become: false
    ansible_connection: local
